INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('case_widgets',0,'demo_nav',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('case_widgets',9,'footer',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('case_widgets',2,'bpm-case-details','<?xml version="1.0" encoding="UTF-8"?><properties><property key="channel">1</property></properties>');
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('case_widgets',4,'bpm-case-roles','<?xml version="1.0" encoding="UTF-8"?><properties><property key="channel">1</property></properties>');
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('case_widgets',5,'bpm-case-comments','<?xml version="1.0" encoding="UTF-8"?><properties><property key="channel">1</property></properties>');
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('case_widgets',6,'bpm-process-diagram','<?xml version="1.0" encoding="UTF-8"?><properties><property key="channel">1</property></properties>');
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('case_widgets',7,'bpm-case-chart','<?xml version="1.0" encoding="UTF-8"?><properties><property key="channel">1</property></properties>');
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('case_widgets',8,'bpm-case-file','<?xml version="1.0" encoding="UTF-8"?><properties><property key="channel">1</property></properties>');
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('task_details',0,'demo_nav',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('task_details',6,'footer',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('new_process',0,'demo_nav',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('case_widgets',3,'bpm-case-progress-status','<?xml version="1.0" encoding="UTF-8"?><properties><property key="showMilestones">true</property><property key="channel">1</property><property key="progressBarType">stacked</property><property key="showNumberOfTasks">true</property></properties>');
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('task_list',0,'demo_nav',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('task_list',6,'footer',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('task_details',2,'PAM_Process_task_detail',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('task_list',2,'bpm-datatable-task-list','<?xml version="1.0" encoding="UTF-8"?><properties><property key="widgetInfoId">466</property></properties>');
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('authhome',6,'footer',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('authhome',0,'demo_nav',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('login',0,'demo_nav',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('login',6,'footer',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('login',2,'login_form',NULL);
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('authhome',2,'bpm-datatable-task-list','<?xml version="1.0" encoding="UTF-8"?><properties><property key="widgetInfoId">480</property></properties>');
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('new_process',2,'bpm-datatype-form','<?xml version="1.0" encoding="UTF-8"?><properties><property key="dataTypeCode">AAA</property><property key="widgetInfoId">440</property><property key="dataUxId">2</property></properties>');
INSERT INTO widgetconfig_draft (pagecode,framepos,widgetcode,config) VALUES ('case_widgets',1,'bpm-case-instance-selector','<?xml version="1.0" encoding="UTF-8"?><properties><property key="channel">1</property><property key="frontEndCaseData">{"container-id":"itorders_1.0.0-SNAPSHOT","knowledge-source-id":"044c21efd4da4ee4984385f03191273c20190827T183715134"}</property></properties>');
